# Generated by Django 6.0.6 on 2026-07-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articulos",
            old_name="autor",
            new_name="autor_articulo",
        ),
    ]
