# Generated by Django 6.0.6 on 2026-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_rename_autor_articulos_autor_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulos",
            name="imagen_articulo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="imagenarticulos/",
                verbose_name="imagenarticulos",
            ),
        ),
    ]
