# Generated by Django 6.0.6 on 2026-07-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_articulos_imagen_articulo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comentarios",
        ),
    ]
