# Generated by Django 6.0.6 on 2026-07-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_delete_comentarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_at", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
