# Generated by Django 6.0.7 on 2026-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulos",
            name="categoria",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
