# Generated by Django 6.0.7 on 2026-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_articulos_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipocategoria", models.CharField(max_length=100)),
            ],
        ),
    ]
