# Generated by Django 6.0.7 on 2026-07-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_categorias"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Articulos",
        ),
        migrations.DeleteModel(
            name="Categorias",
        ),
        migrations.DeleteModel(
            name="Comentarios",
        ),
    ]
