# Generated by Django 6.0.7 on 2026-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("post", "0008_delete_articulos_delete_categorias_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titular", models.CharField(max_length=200)),
                ("articulo", models.TextField()),
                ("autor_articulo", models.CharField(max_length=100)),
                ("fecha_at", models.DateTimeField(auto_now_add=True)),
                ("fecha_up", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "imagen_articulo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imagenarticulos/",
                        verbose_name="imagenarticulos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipocategoria", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_at", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
