# Generated by Django 6.0.6 on 2026-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_autor", models.CharField(max_length=100)),
                ("apellido_autor", models.CharField(max_length=100)),
                ("telefono_autor", models.CharField(max_length=100)),
                ("email_autor", models.EmailField(max_length=50)),
                ("website_autor", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_editor", models.CharField(max_length=100)),
                ("apellido_editor", models.CharField(max_length=100)),
                ("telefono_editor", models.CharField(max_length=50)),
                ("email_editor", models.EmailField(max_length=50)),
                ("website_editor", models.URLField()),
            ],
        ),
    ]
