# Generated by Django 6.0.6 on 2026-07-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autores",
            name="email_autor",
            field=models.EmailField(max_length=254),
        ),
    ]
